### PR TITLE
DAMIEN-100: Basic page layout, dark mode

### PR DESCRIPTION
**Pull request by lyttam**
https://jira-secure.berkeley.edu/browse/DAMIEN-100

### CODE REVIEW

**Comment by pauline2k** [comment]
@lyttam Looks good to me, but does Travis need a kick?

**Comment by lyttam** [comment]
@pauline2k I guess so. Kicked.

**Comment by pauline2k** [comment]
@lyttam I think this failure is coming out of my previous commit; Travis doesn't like being told to do dblink, which, fair enough. Let me see if I can quickly push up a remedy.

**Comment by lyttam** [comment]
Thanks @pauline2k , I'll try it again.

**Pull request merged**
