### PR TITLE
DAMIEN-217: adds user-department form association

### PR DESCRIPTION
**Pull request by lyttam**
https://jira-secure.berkeley.edu/browse/DAMIEN-217

### CODE REVIEW

**Comment by johncrossman** [comment]
Looks good to me and yet Travis complains: `No module damien.models.user_department_form`.  @pauline2k should also review.

**Comment by johncrossman** [comment]
Looks good to me and yet Travis complains: `No module damien.models.user_department_form`.  @pauline2k should also review.

**Comment by pauline2k** [comment]
If there is a user_department_form.py model on top of the join table, perhaps it wasn't checked into git?

**Comment by lyttam** [comment]
@pauline2k that's probably it, I will fix.

**Comment by lyttam** [comment]
Amended, green Travis. @pauline2k @johncrossman

**Pull request merged**
