### PR TITLE
DAMIEN-4: Adds configs, routes, tests, travis

### PR DESCRIPTION
**Pull request by lyttam**
https://jira.ets.berkeley.edu/jira/browse/DAMIEN-4

### CODE REVIEW

**Comment by pauline2k** [comment]
Looks like a web app to me! Thanks for all the work, @lyttam. To round things off, should we try to enable a Travis run on this PR before merge?

**Comment by lyttam** [comment]
@pauline2k Sure, I just sent a github-Travis integration request.

**Comment by lyttam** [comment]
Travis is happy. @pauline2k

**Comment by pauline2k** [comment]
Travis is happy, everyone's happy.

**Pull request merged**
